source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'MSCircleProgressBar_Example', :exclusive => true do
  pod "MSCircleProgressBar", :path => "../"
end

target 'MSCircleProgressBar_Tests', :exclusive => true do
  pod "MSCircleProgressBar", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
